### ISSUE TITLE
Where to find tutorial on programmatically prism with java?

### ISSUE THREAD

**Issue by diolegend** [prismmodelchecker/prism-api#2]

**Comment by diolegend** [comment]
Where to find a tutorial on programmatically prism with java?

**Comment by davexparker** [comment]
You can find instructions and various example programs here:

https://github.com/prismmodelchecker/prism-api/

**Comment by diolegend** [comment]
It is possible to create multiple module like in prism language?

**Comment by davexparker** [comment]
I'm not quite sure what you mean. In principle, you can create a PRISM language model description programmatically, but if you have a structured representation of your model, it's much more straightforward to create a textual model description as a string/file and parse it.

**Comment by diolegend** [comment]
Ok thanks, another question, is it possible to export in prism format file (x.pm) in the example MDPModelGenerator.java?

**Comment by davexparker** [comment]
This is not very commonly used I think, but the explicit engine has some support for generating `.prism` (`.pm`) files after a model has been built. If you make sure you are using the explicit engine (`prism.setEngine(Prism.EXPLICIT);` after initialising PRISM), then you can try `prism.getBuiltModelExplicit().exportToPrismLanguage("model.prism");` after the model has been built (e.g. after model checking has been done, to trigger model construction).

**Comment by williamzhao1999** [comment]
> This is not very commonly used I think, but the explicit engine has some support for generating `.prism` (`.pm`) files after a model has been built. If you make sure you are using the explicit engine (`prism.setEngine(Prism.EXPLICIT);` after initialising PRISM), then you can try `prism.getBuiltModelExplicit().exportToPrismLanguage("model.prism");` after the model has been built (e.g. after model checking has been done, to trigger model construction).

Great, it works, do you have a Discord group where i can ask questions and get help?

**Comment by williamzhao1999** [comment]
In the repo, there aren't any examples to create at least 2 modules and do synchronization from modules programmatically prism with java.
For example
```
ctmc

const int N = 10;
const double mu = 1/10;
const double lambda = 1/2;
const double gamma = 1/3;

module queue
     q : [0..N];

     [] q<N -> mu:(q'=q+1);
     [] q=N -> mu:(q'=q);
     [serve] q>0 -> lambda:(q'=q-1);
endmodule

module server
     s : [0..1];

     [serve] s=0 -> 1:(s'=1);
     [] s=1 -> gamma:(s'=0);
endmodule
```

and synchronization with [serve].

Is it possible to provide one example of this please?

**Comment by davexparker** [comment]
> Great, it works, do you have a Discord group where i can ask questions and get help?

The Google Group for developers is the best option:

https://groups.google.com/g/prismmodelchecker-dev
