### ISSUE TITLE
Is it possible to add an example with synchronization?

### ISSUE THREAD

**Issue by williamzhao1999** [prismmodelchecker/prism-api#4]
In the repo, there aren't any examples to create at least 2 modules and do synchronization from modules programmatically prism with java.
For example

```
ctmc

const int N = 10;
const double mu = 1/10;
const double lambda = 1/2;
const double gamma = 1/3;

module queue
     q : [0..N];

     [] q<N -> mu:(q'=q+1);
     [] q=N -> mu:(q'=q);
     [serve] q>0 -> lambda:(q'=q-1);
endmodule

module server
     s : [0..1];

     [serve] s=0 -> 1:(s'=1);
     [] s=1 -> gamma:(s'=0);
endmodule
```
and synchronization with [serve].

Is it possible to provide one example of this please?

**Comment by davexparker** [comment]
Hi @williamzhao1999. I don't think this is possible at the moment - the only way to use synchronisation between modules is by providing a PRISM language model description.

But out of interest (we are trying to improve the API), what did you have in mind? In particular, how did you plan to create the individual modules that would then be composed?

**Comment by williamzhao1999** [comment]
Thank you @davexparker, I'm trying to replicate https://www.prismmodelchecker.org/casestudies/gossip.php into Java with prism-api, I'm still thinking about how to manage individual modules and then compose.

**Comment by williamzhao1999** [comment]
@davexparker Is there any method to do renaming modules like in prism language with java using programmatically prism-api?

**Comment by davexparker** [comment]
Module renaming is a purely syntactic operation - it only really makes sense to apply this within a PRISM language model, or a fragment of it. Currently, that can only be done using the language.

**Comment by williamzhao1999** [comment]
Thanks @davexparker, how to have the same format of dot file ?

Java generated dot file using `prism.exportTransToFile(true, Prism.EXPORT_DOT, new File("mdp.dot"));`
`digraph S {
node [shape=box];
0 -> n0_0 [ arrowhead=none,label="0:startt1" ];
n0_0 [ shape=point,width=0.1,height=0.1,label="" ];
n0_0 -> 8 [ label="1" ];
0 -> n0_1 [ arrowhead=none,label="1:startt2" ];
n0_1 [ shape=point,width=0.1,height=0.1,label="" ];
n0_1 -> 4 [ label="1" ];
0 -> n0_2 [ arrowhead=none,label="2:startt3" ];
n0_2 [ shape=point,width=0.1,height=0.1,label="" ];
n0_2 -> 2 [ label="1" ];
0 -> n0_3 [ arrowhead=none,label="3:startt4" ];
n0_3 [ shape=point,width=0.1,height=0.1,label="" ];
n0_3 -> 1 [ label="1" ];
1 -> n1_0 [ arrowhead=none,label="0:startt1" ];
n1_0 [ shape=point,width=0.1,height=0.1,label="" ];
n1_0 -> 9 [ label="1" ];
1 -> n1_1 [ arrowhead=none,label="1:startt2" ];
n1_1 [ shape=point,width=0.1,height=0.1,label="" ];
n1_1 -> 5 [ label="1" ];
1 -> n1_2 [ arrowhead=none,label="2:startt3" ];
n1_2 [ shape=point,width=0.1,height=0.1,label="" ];
n1_2 -> 3 [ label="1" ];
2 -> n2_0 [ arrowhead=none,label="0:startt4" ];
n2_0 [ shape=point,width=0.1,height=0.1,label="" ];
n2_0 -> 10 [ label="1" ];
2 -> n2_1 [ arrowhead=none,label="1:startt2" ];
n2_1 [ shape=point,width=0.1,height=0.1,label="" ];
n2_1 -> 6 [ label="1" ];
2 -> n2_2 [ arrowhead=none,label="2:startt4" ];
n2_2 [ shape=point,width=0.1,height=0.1,label="" ];
n2_2 -> 3 [ label="1" ];
3 -> n3_0 [ arrowhead=none,label="0:startt1" ];
n3_0 [ shape=point,width=0.1,height=0.1,label="" ];
n3_0 -> 11 [ label="1" ];
3 -> n3_1 [ arrowhead=none,label="1:startt2" ];
n3_1 [ shape=point,width=0.1,height=0.1,label="" ];
n3_1 -> 7 [ label="1" ];
4 -> n4_0 [ arrowhead=none,label="0:startt4" ];
n4_0 [ shape=point,width=0.1,height=0.1,label="" ];
n4_0 -> 12 [ label="1" ];
4 -> n4_1 [ arrowhead=none,label="1:startt3" ];
n4_1 [ shape=point,width=0.1,height=0.1,label="" ];
n4_1 -> 6 [ label="1" ];
4 -> n4_2 [ arrowhead=none,label="2:startt4" ];
n4_2 [ shape=point,width=0.1,height=0.1,label="" ];
n4_2 -> 5 [ label="1" ];
5 -> n5_0 [ arrowhead=none,label="0:startt1" ];
n5_0 [ shape=point,width=0.1,height=0.1,label="" ];
n5_0 -> 13 [ label="1" ];
5 -> n5_1 [ arrowhead=none,label="1:startt3" ];
n5_1 [ shape=point,width=0.1,height=0.1,label="" ];
n5_1 -> 7 [ label="1" ];
6 -> n6_0 [ arrowhead=none,label="0:startt4" ];
n6_0 [ shape=point,width=0.1,height=0.1,label="" ];
n6_0 -> 14 [ label="1" ];
6 -> n6_1 [ arrowhead=none,label="1:startt4" ];
n6_1 [ shape=point,width=0.1,height=0.1,label="" ];
n6_1 -> 7 [ label="1" ];
7 -> n7_0 [ arrowhead=none,label="0:startt1" ];
n7_0 [ shape=point,width=0.1,height=0.1,label="" ];
n7_0 -> 15 [ label="1" ];
8 -> n8_0 [ arrowhead=none,label="0:startt4" ];
n8_0 [ shape=point,width=0.1,height=0.1,label="" ];
n8_0 -> 12 [ label="1" ];
8 -> n8_1 [ arrowhead=none,label="1:startt3" ];
n8_1 [ shape=point,width=0.1,height=0.1,label="" ];
n8_1 -> 10 [ label="1" ];
8 -> n8_2 [ arrowhead=none,label="2:startt4" ];
n8_2 [ shape=point,width=0.1,height=0.1,label="" ];
n8_2 -> 9 [ label="1" ];
9 -> n9_0 [ arrowhead=none,label="0:startt2" ];
n9_0 [ shape=point,width=0.1,height=0.1,label="" ];
n9_0 -> 13 [ label="1" ];
9 -> n9_1 [ arrowhead=none,label="1:startt3" ];
n9_1 [ shape=point,width=0.1,height=0.1,label="" ];
n9_1 -> 11 [ label="1" ];
10 -> n10_0 [ arrowhead=none,label="0:startt4" ];
n10_0 [ shape=point,width=0.1,height=0.1,label="" ];
n10_0 -> 14 [ label="1" ];
10 -> n10_1 [ arrowhead=none,label="1:startt4" ];
n10_1 [ shape=point,width=0.1,height=0.1,label="" ];
n10_1 -> 11 [ label="1" ];
11 -> n11_0 [ arrowhead=none,label="0:startt2" ];
n11_0 [ shape=point,width=0.1,height=0.1,label="" ];
n11_0 -> 15 [ label="1" ];
12 -> n12_0 [ arrowhead=none,label="0:startt4" ];
n12_0 [ shape=point,width=0.1,height=0.1,label="" ];
n12_0 -> 14 [ label="1" ];
12 -> n12_1 [ arrowhead=none,label="1:startt4" ];
n12_1 [ shape=point,width=0.1,height=0.1,label="" ];
n12_1 -> 13 [ label="1" ];
13 -> n13_0 [ arrowhead=none,label="0:startt3" ];
n13_0 [ shape=point,width=0.1,height=0.1,label="" ];
n13_0 -> 15 [ label="1" ];
14 -> n14_0 [ arrowhead=none,label="0:startt4" ];
n14_0 [ shape=point,width=0.1,height=0.1,label="" ];
n14_0 -> 15 [ label="1" ];
15 -> n15_0 [ arrowhead=none,label="0:startt1" ];
n15_0 [ shape=point,width=0.1,height=0.1,label="" ];
n15_0 -> 15 [ label="1" ];
}
`

Prism exported dot file with states:
`digraph LTS {
node [label="",shape="box"];
0 [label="0"];
0 -> 8 [label="0:start1"];
0 -> 4 [label="1:start2"];
0 -> 2 [label="2:start3"];
0 -> 1 [label="3:start4"];
1 [label="1"];
1 -> 9 [label="0:start1"];
1 -> 5 [label="1:start2"];
1 -> 3 [label="2:start3"];
2 [label="2"];
2 -> 10 [label="0:start1"];
2 -> 6 [label="1:start2"];
2 -> 3 [label="2:start4"];
3 [label="3"];
3 -> 11 [label="0:start1"];
3 -> 7 [label="1:start2"];
4 [label="4"];
4 -> 12 [label="0:start1"];
4 -> 6 [label="1:start3"];
4 -> 5 [label="2:start4"];
5 [label="5"];
5 -> 13 [label="0:start1"];
5 -> 7 [label="1:start3"];
6 [label="6"];
6 -> 14 [label="0:start1"];
6 -> 7 [label="1:start4"];
7 [label="7"];
7 -> 15 [label="0:start1"];
8 [label="8"];
8 -> 12 [label="0:start2"];
8 -> 10 [label="1:start3"];
8 -> 9 [label="2:start4"];
9 [label="9"];
9 -> 13 [label="0:start2"];
9 -> 11 [label="1:start3"];
10 [label="10"];
10 -> 14 [label="0:start2"];
10 -> 11 [label="1:start4"];
11 [label="11"];
11 -> 15 [label="0:start2"];
12 [label="12"];
12 -> 14 [label="0:start3"];
12 -> 13 [label="1:start4"];
13 [label="13"];
13 -> 15 [label="0:start3"];
14 [label="14"];
14 -> 15 [label="0:start4"];
15 [label="15"];
15 -> 15 [label="0"];
}
`

**Comment by williamzhao1999** [comment]
Thanks @davexparker, is it possible to have a simple documentation of available functions?

**Comment by davexparker** [comment]
From the API side, the documentation is primarily JavaDoc (which is mostly quite good) and code examples.

**Comment by williamzhao1999** [comment]
Many thanks @davexparker  for help

**Comment by williamzhao1999** [comment]
@davexparker Thanks for everything, I realized that is it possible to create every model, because I replicated the gossip model in Java programmatically.
I close this issue.
